apiVersion: apps/v1
kind: Deployment
metadata:
  name: length-service
  labels:
    app: length-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: length-service
  template:
    metadata:
      labels:
        app: length-service
    spec:
      containers:
        - name: length-service
          image: length-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - configMapRef:
                name: length-config